export const defaultProps = {
    dataTableBorderPosition: 'content',
    rowsPerPageOptions: [2, 5, 10, 20, 50, 100],
    rowsPerPagePosition: 'top',
    rowsPerPageDefault: 10,
    rowsPerPageLabel: 'Rows per page',
    rowsPerPageTextAfter: '',
    searchBar: true,
    searchBarPlaceholder: 'Search',
    fontFamily: 'Roboto, RobotoDraft, Helvetica, Arial, sans-serif',
    showPagination: true,
    dataTableCellMinWidth: '6em',
    showdataTableHeader: true,
    dataTableRowsBorder: false,
    dataTableRowsHeight: '3rem',
    showDataTableRowCard: true,
}
