export const defaultProps = {
    // rowsPerPageOptions: [10, 25, 50, 100],
    dataTableBorderPosition: 'content',
    rowsPerPageOptions: [5, 10, 20, 50, 100],
    rowsPerPagePosition: 'top',
    rowsPerPageDefault: 10,
    rowsPerPageLabel: 'Rows per page',
    rowsPerPageTextAfter: '',
    searchBar: true,
    searchBarPlaceholder: 'Search',
    fontFamily: 'Roboto, RobotoDraft, Helvetica, Arial, sans-serif',
    pagination: true,
    dataTableCellMinWidth: '6em',
    showHeader: true,
    dataTableRowsBorder: false,
    dataTableRowsHeight: '3em',
}
